version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: pull_requests_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # run init
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "9099:80"  # Access pgAdmin at http://localhost:9099
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - pgnetwork

volumes:
  pg_data:
  pgadmin_data:

networks:
  pgnetwork:
    driver: bridge
